import type { MetadataRoute } from 'next';

// Web App Manifest. Next.js serves this at /manifest.webmanifest and
// auto-injects the <link rel="manifest"> tag in the document head.
//
// For the install banner on Android/Chrome to fire automatically we need
// at least a 192×192 and 512×512 maskable PNG, plus a registered service
// worker. Both are below — see app/icon-192.tsx, app/icon-512.tsx,
// app/apple-icon.tsx, and public/sw.js.

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'Estación 33',
    short_name: 'Estación 33',
    description:
      'Hamburguesas, hot dogs y pasta italiana en Iguala, Gro. — pedidos y reparto.',
    lang: 'es-MX',
    dir: 'ltr',
    start_url: '/',
    scope: '/',
    display: 'standalone',
    orientation: 'portrait',
    background_color: '#0A0A0A',
    theme_color: '#0A0A0A',
    categories: ['food', 'shopping'],
    icons: [
      {
        src: '/burger-favicon.svg',
        type: 'image/svg+xml',
        sizes: 'any',
        purpose: 'any',
      },
      // 192 + 512 PNGs are generated by app/icon-192/route.tsx and
      // app/icon-512/route.tsx via ImageResponse. We register each twice
      // — once as `any` and once as `maskable` — because Next.js's
      // manifest type only accepts a single purpose per entry, while the
      // Web App Manifest spec wants both.
      {
        src: '/icon-192',
        type: 'image/png',
        sizes: '192x192',
        purpose: 'any',
      },
      {
        src: '/icon-192',
        type: 'image/png',
        sizes: '192x192',
        purpose: 'maskable',
      },
      {
        src: '/icon-512',
        type: 'image/png',
        sizes: '512x512',
        purpose: 'any',
      },
      {
        src: '/icon-512',
        type: 'image/png',
        sizes: '512x512',
        purpose: 'maskable',
      },
    ],
    // Once phase 6 adds shortcuts to /repartidor and /admin/ordenes,
    // we can register them here for long-press app icon menus.
    shortcuts: [
      {
        name: 'Cola de pedidos',
        short_name: 'Cola',
        url: '/repartidor',
      },
      {
        name: 'Pedidos (admin)',
        short_name: 'Pedidos',
        url: '/admin/ordenes',
      },
      {
        name: 'Menú',
        short_name: 'Menú',
        url: '/menu',
      },
    ],
  };
}
